M48
; DRILL file {KiCad 9.0.2} date 2026-04-11T12:26:04+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-11T12:26:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X3.986Y-3.776
X3.986Y-4.0035
T2
X3.8126Y-4.6228
M30
